version: '2.3'
services:
  matchvec:
    container_name: ${USER}-matchvec
    build:
      context: ./docker/cpu
      args:
        - http_proxy=${http_proxy}
        - https_proxy=${http_proxy}
    env_file:
      - docker/env.list
    environment:
      - http_proxy=${http_proxy}
      - https_proxy=${http_proxy}
      - no_proxy=${no_proxy}
    expose:
      - ${APP_PORT}
    volumes:
      - ./:/app
      - ${MODEL_PATH}:/model
    networks:
      - isolated_nw
    labels:
      - traefik.enable=true
      - traefik.backend=matchvec
      - traefik.port=5000
      - traefik.frontend.rule=PathPrefix:/docs,/api,/swaggerui

networks:
  isolated_nw:
    external:
      name: isolated_nw
