version: '2.3'
services:
   matchvec:
    container_name: ${USER}-matchvec
    build:
      context: ./docker/torch-flask
    env_file:
      - docker/env.list
    environment:
     - TORCH_HOME=/model
    ports:
     - ${APP_PORT}:5000
    volumes:
     - ./:/app
     - ./model:/model
