version: '2.3'
services:
   matchvec:
    container_name: ${USER}-matchvec
    build:
      context: ./docker/torch-flask
      args:
      - http_proxy=${http_proxy}
      - https_proxy=${https_proxy}
    env_file:
      - docker/env.list
    environment:
     - TORCH_MODEL_ZOO=/model
     - http_proxy=${http_proxy}
     - https_proxy=${http_proxy}
     - no_proxy=${no_proxy}
    ports:
     - ${APP_PORT}:5000
    volumes:
     - ./:/app
     - ./model:/model
