version: '2.3'
services:
   matchvec:
    container_name: ${USER}-matchvec
    build:
      context: ./docker/torch-flask
    cpus : 2
    ipc: host
    env_file:
      - docker/env.list
    environment:
     - TORCH_MODEL_ZOO=/model
    ports:
     - ${APP_PORT}:5000
    volumes:
     - ./:/app
     - /home/model:/model
    command: "python app.py"
